version: "3"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    tty: true
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis

  worker:
    build:
      context: celery_queue
      dockerfile: Dockerfile
    depends_on:
      - redis

  monitor:
    build:
      context: celery_queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis

  mailhog:
    image: mailhog/mailhog
    # command: -invite-jim -jim-accept=0.5
    ports:
      - "8025:8025" 
      - "1025:1025"

  redis:
    image: redis
    ports:
      - "6379:6379"
 